# Generated by Django 4.2.6 on 2023-10-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VendorName', models.CharField(max_length=122)),
                ('VendorAddress', models.TextField()),
                ('VendorImage', models.ImageField(upload_to='ProfileImage')),
                ('BusinessName', models.CharField(max_length=122)),
                ('BusinessAddress', models.TextField(max_length=122)),
                ('GstNumber', models.CharField(max_length=122, null=True)),
                ('BusinessLogo', models.ImageField(upload_to='Logo')),
            ],
        ),
    ]
