# Generated by Django 4.2 on 2023-10-23 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_productinformation_productdesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformation',
            name='EmailId',
            field=models.CharField(default=2, max_length=122),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='MobileNumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinformation',
            name='Password',
            field=models.CharField(default=1, max_length=122),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinformation',
            name='GstNumber',
            field=models.CharField(default='No GST Number', max_length=122, null=True),
        ),
    ]
