# Generated by Django 4.2 on 2023-10-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_userinformation_emailid_userinformation_mobilenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileVerificationNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileNumber', models.IntegerField()),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
