# Generated by Django 4.2 on 2023-10-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_mobileverificationnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerBuinsessInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessName', models.CharField(max_length=122)),
                ('GstNumber', models.CharField(max_length=122, null=True)),
                ('Password', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='SellerInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SellerName', models.CharField(max_length=122)),
                ('DOB', models.DateField()),
            ],
        ),
    ]
