# Generated by Django 4.2 on 2023-10-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0006_sellerbuinsessinformation_sellerinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerbuinsessinformation',
            name='Primary_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sellerinformation',
            name='Primary_key',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileverificationnumber',
            name='MobileNumber',
            field=models.CharField(max_length=122),
        ),
    ]
