# Generated by Django 4.2.6 on 2023-10-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0007_sellerbuinsessinformation_primary_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerbuinsessinformation',
            name='Primary_key',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='sellerinformation',
            name='Primary_key',
            field=models.CharField(max_length=122),
        ),
    ]
