# Generated by Django 4.2 on 2023-10-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0009_alter_sellerinformation_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='Password',
        ),
    ]
