# Generated by Django 4.2 on 2023-10-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_remove_userinformation_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinformation',
            name='BusinessLogo',
        ),
    ]
